apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: ia-hattorihrd-ns-tekton
  labels:
    app: node-app
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: node-app
