version: '2'
services:
  ansible:
          build: 
            context : ./ansible
            dockerfile : Dockerfile
          container_name: ansible
          tty: true
          stdin_open: true
          privileged: true
  node-app:
          build:
            context : ./node-app
            dockerfile : Dockerfile
          container_name: node-app
          tty: true
          stdin_open: true
          privileged: true
